FROM python:3.9-slim

COPY requirements.txt requirements.txt
COPY api/commande_api.py app/commande_api.py

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

CMD ["uvicorn", "commande_api:app", "--host", "0.0.0.0", "--port", "8886"]
